name: OH-PA Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform Action'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

permissions:
  id-token: write
  contents: read

jobs:
  lint-security:
    name: Lint and Security Check (OH-PA)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run TFLint
        run: |
          curl -sSL https://github.com/terraform-linters/tflint/releases/latest/download/tflint_linux_amd64.zip -o tflint.zip
          unzip tflint.zip
          sudo mv tflint /usr/local/bin/
          tflint --init && tflint -f compact

      - name: Run Checkov (Soft Fail)
        run: |
          pip install checkov
          checkov --directory . --soft-fail

  terraform:
    name: OH-PA Terraform ${{ github.event.inputs.action }}
    runs-on: ubuntu-latest
    needs: lint-security

    env:
      AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::654654225250:role/githubactions-assume-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan (Save to File)
        run: terraform plan -out=tfplan.binary

      - name: Show Terraform Plan Summary
        if: github.event.inputs.action == 'apply'
        run: terraform show -no-color tfplan.binary

      - name: Terraform Apply from Plan (OH-PA)
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve tfplan.binary

      - name: Terraform Destroy (OH-PA)
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve
